# https://pub.dev/packages/pedantic_mono
include: package:flutter_lints/flutter.yaml
linter:
  rules:
    - require_trailing_commas
    - always_use_package_imports: true
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
  errors:
    invalid_annotation_target: ignore