name: ous
description: 岡山理科大学の非公式アプリ
publish_to: 'none' 
version: 2.3.2+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.31.0
  url_launcher: ^6.1.10
  http: ^0.13.5
  flutter_screenutil: ^5.7.0
  settings_ui: ^2.0.2
  firebase_auth: ^4.19.5
  firebase_storage: ^11.7.5
  image_picker: ^0.8.7+3
  in_app_review: ^2.0.6
  google_sign_in: ^6.2.1
  path: ^1.8.2
  cloud_firestore: ^4.17.3
  shared_preferences: ^2.1.0
  syncfusion_flutter_gauges: ^20.4.54
  package_info_plus: ^8.0.0
  fluttertoast: ^8.2.6
  sign_in_with_apple: ^6.1.0
  flutter_native_splash: ^2.2.0+1
  flutter_overboard: ^3.1.1
  uuid: ^3.0.7
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  flutter_staggered_animations: ^1.1.1
  flutter_speed_dial: ^7.0.0
  flutter_launcher_icons: ^0.13.1
  slide_to_act: ^2.0.1
  markdown_widget: ^2.2.0
  dio: ^5.3.3
  firebase_remote_config: ^4.4.5
  firebase_analytics: ^10.10.5
  flutter_riverpod: ^2.4.10
  cupertino_icons: ^1.0.6
  shimmer: ^3.0.0
  fl_chart: ^0.66.2
  share_plus: ^8.0.2
  font_awesome_flutter: ^10.7.0
  screenshot: ^2.3.0
  google_fonts: ^4.0.4
  mobile_scanner: ^4.0.1
  xml: ^6.5.0
  riverpod_annotation: ^2.3.5
  freezed_annotation: ^2.4.1
  path_provider: ^2.1.3
  html: ^0.15.4
  webview_flutter: ^4.7.0
  supabase_flutter: ^2.5.3
  flutter_dotenv: ^5.1.0
  image_cropper: ^4.0.1
  flutter_local_notifications: ^17.2.1+2
  rotated_corner_decoration: ^2.1.0+1
  cached_network_image: ^3.3.1
  google_mobile_ads: ^5.1.0
  app_tracking_transparency: ^2.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: any
  riverpod_generator: ^2.4.0
  build_runner: ^2.4.8
  custom_lint: ^0.6.2
  riverpod_lint: ^2.3.10
  freezed: ^2.4.7  
  json_serializable: ^6.7.1
  slang_build_runner: ^3.29.0
  pedantic_mono: any
  flutter_gen_runner: ^5.4.0
  import_sorter: ^4.6.0
  flutter_lints: ^2.0.1
  
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icon/

flutter_native_splash:
  color: '#ffffff'
  image: 'assets/icon/icon.png'
  color_dark: '#202124'
  image_dark: 'assets/icon/icon_dark.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/icon/icon.png'
    icon_background_color_dark: '#202124'
    image_dark: 'assets/icon/icon_dark.png'

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
