name: ous
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.7.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  firebase_core: ^2.27.0
  url_launcher: ^6.1.10
  flutter_launcher_icons: ^0.11.0
  http: ^0.13.5
  html: ^0.15.2
  flutter_screenutil: ^5.7.0
  settings_ui: ^2.0.2
  firebase_auth: ^4.17.8
  firebase_storage: ^11.1.0
  image_picker: ^0.8.7+3
  in_app_review: ^2.0.6
  google_sign_in: ^6.1.0
  path: ^1.8.2
  syncfusion_flutter_pdfviewer: ^20.4.54
  flutter_inappwebview: 
    git:
      url: https://github.com/Estrelio/flutter_inappwebview.git
      ref: fix-xcode-17  
  cloud_firestore: ^4.15.8
  shared_preferences: ^2.1.0
  syncfusion_flutter_gauges: ^20.4.54
  package_info_plus: ^3.1.0
  fluttertoast: ^8.2.1



  google_fonts: ^4.0.4
  sign_in_with_apple: ^4.3.0
  flutter_native_splash: ^2.2.0+1
  flutter_overboard: ^3.1.1
  uuid: ^3.0.7
  share: ^2.0.4
  map_launcher: ^2.5.0+1
  rxdart: ^0.27.7
  share_extend: ^2.0.0
  flutter_localizations:
    sdk: flutter
  intl: ^0.18.0
  flutter_staggered_animations: ^1.1.1
  flutter_speed_dial: ^7.0.0
  carousel_slider: ^4.2.1
  slide_to_act: ^2.0.1
  markdown_widget: ^2.2.0
  build_runner: ^2.4.6
  dio: ^5.3.3
  xml: ^6.3.0
  firebase_remote_config: ^4.3.3
  firebase_analytics: ^10.7.4
  device_preview: ^1.1.0
  uni_links: ^0.5.1
  flutter_riverpod: ^2.4.10
  cupertino_icons: ^1.0.6
dev_dependencies:
  flutter_test:
    sdk: flutter
  dependency_validator: any
  import_sorter: ^4.6.0
  pedantic_mono: any







  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.1
flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/icon/
flutter_native_splash:
  color: '#ffffff'
  image: 'assets/images/icon.png'
  color_dark: '#202124'
  image_dark: 'assets/icon/icon_dark.png'
  fullscreen: true
  android_12:
    icon_background_color: '#ffffff'
    image: 'assets/icon/icon.png'
    icon_background_color_dark: '#202124'
    image_dark: 'assets/icon/icon_dark.png'


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
