// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD90_eEKX77kuB3EwrFIRwfwaKg9CCtUkA',
    appId: '1:550367521697:web:74fd75c267af0084a539e0',
    messagingSenderId: '550367521697',
    projectId: 'ous-unoffical-20d2c',
    authDomain: 'ous-unoffical-20d2c.firebaseapp.com',
    databaseURL: 'https://ous-unoffical-20d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ous-unoffical-20d2c.appspot.com',
    measurementId: 'G-R1WL62KTPR',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWTdKyY5SV2JuL2lcYcjUZjMTHJhbylLw',
    appId: '1:550367521697:android:4ac0dd32af43f5e8a539e0',
    messagingSenderId: '550367521697',
    projectId: 'ous-unoffical-20d2c',
    databaseURL: 'https://ous-unoffical-20d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ous-unoffical-20d2c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzpNrYyg5yDqkTobE4PBYjc1s3kAgBaw0',
    appId: '1:550367521697:ios:dee6af6b9a1392aba539e0',
    messagingSenderId: '550367521697',
    projectId: 'ous-unoffical-20d2c',
    databaseURL: 'https://ous-unoffical-20d2c-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'ous-unoffical-20d2c.appspot.com',
    androidClientId: '550367521697-5lenfmij8k9bdojaamhffo9pcvs4143n.apps.googleusercontent.com',
    iosClientId: '550367521697-bi8fc20atnpnvmtsrrna49tjmed3h83i.apps.googleusercontent.com',
    iosBundleId: 'com.ous.unoffical.app',
  );
}
