// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCVwMB1kr4eyv0VDraREYl4o7VCnNRlndw',
    appId: '1:701179487640:web:132767aefb0dacd580b7ed',
    messagingSenderId: '701179487640',
    projectId: 'ous-app-8b971',
    authDomain: 'ous-app-8b971.firebaseapp.com',
    storageBucket: 'ous-app-8b971.appspot.com',
    measurementId: 'G-BMR49RNX1V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtlIgmc2mWmTunXbXJzf8xmyJNXF5ej00',
    appId: '1:701179487640:android:41b5962a900b11e580b7ed',
    messagingSenderId: '701179487640',
    projectId: 'ous-app-8b971',
    storageBucket: 'ous-app-8b971.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVLToj9tc5fmDqE4Ni3J4JCXY05Gc7Sio',
    appId: '1:701179487640:ios:61f5d44aa4f97c4b80b7ed',
    messagingSenderId: '701179487640',
    projectId: 'ous-app-8b971',
    storageBucket: 'ous-app-8b971.appspot.com',
    androidClientId: '701179487640-imvgicnpkj8n1md178eicjccfcb5v1al.apps.googleusercontent.com',
    iosClientId: '701179487640-ns65rh2t10ucm8i7lrfgpthba13pa2ki.apps.googleusercontent.com',
    iosBundleId: 'com.ous.unoffical.app',
  );

}